Symfony 5 compatibility
facile-it/symfony-functional-testcase pull request #2
Opened 2020-02-21 15:17 UTC by gianiaz

2020-02-21 15:28 UTC, Jean85 requested changes
We also need a changelog entry!

2020-02-21 15:28 UTC, Jean85 commented on composer.json
>          "symfony/phpunit-bridge": "^4.2",
I would update this to 5.0, since it does not conflict with Symfony components
```suggestion
        "symfony/phpunit-bridge": "^5.0",
```

2020-02-24 08:24 UTC, gianiaz commented
> We also need a changelog entry!

Done! :-)

2020-02-24 13:23 UTC, Jean85 approved these changes

2020-02-24 13:23 UTC, merged